# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 06:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(default='local', max_length=30)),
                ('drink_type', models.CharField(choices=[('soft drink', 'soft drink'), ('hard drink', 'hard drink')], default='soft drink', max_length=30)),
                ('available', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['drink_type'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('food_type', models.CharField(blank=True, help_text='Eg: Italian, Continental, Asian', max_length=30, null=True)),
                ('course', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'linch'), ('snacks', 'snacks'), ('dinner', 'dinner')], default='snacks', max_length=30)),
                ('price', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['course'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Drink')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
