# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='beverage',
        ),
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.AddField(
            model_name='drink',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Order'),
        ),
        migrations.AddField(
            model_name='food',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Order'),
        ),
        migrations.AlterField(
            model_name='food',
            name='course',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('snacks', 'snacks'), ('dinner', 'dinner')], default='snacks', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
