# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20171126_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Order'),
        ),
        migrations.AlterField(
            model_name='food',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Order'),
        ),
    ]
