# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='descriptionm',
            field=models.TextField(blank=True, help_text='Enter a short description of this drink', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/drink'),
        ),
        migrations.AddField(
            model_name='food',
            name='descriptionm',
            field=models.TextField(blank=True, help_text='Enter a short description of this food', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/food'),
        ),
    ]
